baseURL = "https://git-workshop.epages.works/"
languageCode = "de-de"
title = "Git Workshop"
theme = "workshop-materials"
defaultContentLanguage = "de"

[params]
  subject = "Git"
  feedbackLink = "https://github.com/ePages-de/git-workshop/issues/new"
